# Generated by Django 6.0.3 on 2026-04-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
