# Generated by Django 6.0.3 on 2026-04-07 04:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
