# Generated by Django 6.0.3 on 2026-04-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_poster_alter_movie_video_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='poster',
            new_name='poster_file',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='image_url',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, help_text='Direct Image Link dalo', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube Watch link dalo', max_length=1000, null=True),
        ),
    ]
