# Generated by Django 6.0.3 on 2026-04-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_rename_poster_movie_poster_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('Trending', 'Trending Now'), ('Action', 'Action Movies'), ('Comedy', 'Comedy'), ('Horror', 'Horror')], default='Trending', max_length=50),
        ),
    ]
