# Generated by Django 6.0.3 on 2026-04-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_category_remove_movie_category_movie_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AddField(
            model_name='movie',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Film'), ('series', 'Web Series'), ('documentary', 'Documentary')], default='movie', help_text='Select karein ki ye Film hai, Series ya Documentary', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
