# Generated by Django 6.0.3 on 2026-04-12 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_category_options_movie_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Film'), ('series', 'Web Series'), ('documentary', 'Documentary'), ('kids', 'Kids Content')], default='movie', help_text='Select karein ki ye Film hai, Series ya Documentary', max_length=20),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_on'],
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
