# Generated by Django 6.0.3 on 2026-04-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_movie_content_type_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, help_text='Cloudinary ka direct video link yahan dalo', max_length=1000, null=True),
        ),
    ]
